- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- ios/Podfile.lock
- lib/landing_screen.dart
- lib/navigation/navigation_screen.dart
- lib/positioning/positioning.dart
- lib/route_preferences/pedestrian_options_screen.dart
- lib/routing/route_details_screen.dart
- lib/routing/routing_screen.dart
- lib/search/search_results_screen.dart
- pubspec.lock
Signed-off-by: Vitalii Khoruzhyi <ext-vitalii.khoruzhyi@here.com>
> Upgraded HERE SDK version to 4.8.0

- lib/common/ui_style.dart
- lib/common/util.dart
- lib/l10n/app_en.arb
- lib/landing_screen.dart
> Added version information into main menu header

- lib/navigation/navigation_screen.dart
> Fixed background navigation using simulation under iOS

- ios/Podfile.lock
- lib/common/gradient_elevated_button.dart
- lib/common/ui_style.dart
- lib/common/util.dart
- lib/download_maps/download_maps_screen.dart
- lib/download_maps/map_loader_controller.dart
- lib/download_maps/map_loader_dialogs.dart
- lib/download_maps/map_region_tile_widget.dart
- lib/download_maps/map_regions_list_screen.dart
- lib/download_maps/storage_space_widget.dart
- lib/l10n/app_en.arb
- lib/landing_screen.dart
- lib/main.dart
- lib/navigation/navigation_dialogs.dart
- lib/routing/routing_screen.dart
- pubspec.lock
- pubspec.yaml
> Implemented offline map loading feature

- lib/l10n/app_en.arb
> Renamed maps download button

- README.md
- android/app/src/main/AndroidManifest.xml
- ios/.gitignore
- ios/Flutter/AppFrameworkInfo.plist
- ios/Podfile.lock
- lib/navigation/navigation_screen.dart
- pubspec.lock
- pubspec.yaml
> Supported Flutter version updated to 2.5.2

- ios/Podfile.lock
- lib/route_preferences/avoidance/country_avoidance_screen.dart
- lib/route_preferences/avoidance/road_features_avoidance_screen.dart
- lib/routing/route_poi_handler.dart
- pubspec.lock
> Upgraded HERE SDK version to 4.9.0

- lib/navigation/navigation_screen.dart
> Disabled camera tracking when panning a map in navigation

- lib/common/application_preferences.dart
- lib/common/place_actions_popup.dart
- lib/common/util.dart
- lib/download_maps/map_loader_dialogs.dart
- lib/l10n/app_en.arb
- lib/landing_screen.dart
- lib/main.dart
- lib/navigation/navigation_dialogs.dart
- lib/navigation/navigation_screen.dart
- lib/navigation/rerouting_handler.dart
- lib/routing/route_poi_handler.dart
- lib/routing/routing_screen.dart
- lib/search/place_details_popup.dart
- lib/search/recent_search_data_model.dart
- lib/search/search_engine_proxy.dart
- lib/search/search_popup.dart
> Added offline mode

- lib/download_maps/download_maps_screen.dart
- lib/download_maps/map_loader_controller.dart
- lib/download_maps/map_loader_dialogs.dart
- lib/download_maps/map_update_progress_widget.dart
- lib/l10n/app_en.arb
> Integrated offline map updater

- lib/route_preferences/transport_modes_widget.dart
- lib/routing/routing_screen.dart
> Hidden unsupported routing modes when the app is offline

- ios/Podfile.lock
- lib/common/application_preferences.dart
- pubspec.lock
- pubspec.yaml
> Implemented saving application preferences.

- lib/landing_screen.dart
- lib/main.dart
- lib/positioning/positioning.dart
- lib/positioning/positioning_engine.dart
- lib/routing/routing_screen.dart
- lib/search/search_results_screen.dart
> Implemented detection of the status of device location services

- lib/search/recent_search_data_model.dart
> Fixed the code for updating the database of recent searches

- lib/landing_screen.dart
- lib/positioning/positioning.dart
> Fixed missing positioning toast during startup

- README.md
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- pubspec.lock
> Updated flutter to version 2.8.0

- ios/Podfile.lock
- pubspec.lock
- pubspec.yaml
> Updated all dependencies

- README.md
- ios/Podfile.lock
- lib/navigation/navigation_screen.dart
- pubspec.lock
- pubspec.yaml
> Upgraded HERE SDK version to 4.10.0

- lib/common/ui_style.dart
- lib/navigation/navigation_screen.dart
- lib/navigation/rerouting_handler.dart
- lib/route_preferences/avoidance/country_avoidance_screen.dart
- lib/route_preferences/avoidance/road_features_avoidance_screen.dart
- lib/route_preferences/avoidance/route_avoidance_options_widget.dart
- lib/route_preferences/dropdown_widget.dart
- lib/route_preferences/numeric_text_field_widget.dart
- lib/route_preferences/preferences_disclosure_row_widget.dart
- lib/route_preferences/route_preferences_screen.dart
- lib/route_preferences/route_text_options_widget.dart
- lib/route_preferences/scooter_options_screen.dart
- lib/route_preferences/transport_modes_widget.dart
- lib/route_preferences/truck_hazardous_goods_screen.dart
- lib/route_preferences/truck_options_screen.dart
- lib/route_preferences/truck_specifications_screen.dart
- lib/routing/routing_screen.dart
> Removed deprecated and redundant code

- ios/Runner/Base.lproj/LaunchScreen.storyboard
- lib/common/util.dart
- pubspec.yaml
> Updated version number

- android/app/src/main/kotlin/com/example/RefApp/FlutterForegroundService.kt
> Fixed crash on Android 12

- lib/route_preferences/car_options_screen.dart
- lib/route_preferences/pedestrian_options_screen.dart
- lib/route_preferences/scooter_options_screen.dart
- lib/route_preferences/truck_options_screen.dart
> Fixed layout of route options screens

- lib/routing/routing_screen.dart
> Hid route details view for offline mode

- lib/route_preferences/route_preferences_screen.dart
- lib/routing/routing_screen.dart
> Hid options for unsupported transport modes in offline mode

- lib/navigation/navigation_screen.dart
> Bad visual experience during rerouting

- lib/common/place_actions_popup.dart
- lib/routing/route_poi_handler.dart
- lib/routing/routing_screen.dart
- lib/search/search_popup.dart
'new' keyword is obsolete in Dart. It doesn't do anything.
> Don't use obsolete 'new' keyword

- lib/common/application_preferences.dart
- lib/common/util.dart
- lib/navigation/navigation_screen.dart
- lib/routing/routing_screen.dart
> Ref app no longer consumes data for traffic in offline mode

- README.md
- ios/Podfile.lock
- lib/download_maps/download_maps_screen.dart
- lib/download_maps/map_loader_controller.dart
- lib/download_maps/map_regions_list_screen.dart
- lib/download_maps/storage_space_widget.dart
- lib/main.dart
- pubspec.lock
> Integrated HERE SDK 4.12

- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
> Fix for runtime JAR files incompatible version warning during apk build

- lib/common/draggable_popup_here_logo_helper.dart
- lib/common/place_actions_popup.dart
- lib/common/ui_style.dart
- lib/download_maps/download_maps_screen.dart
- lib/download_maps/map_loader_controller.dart
- lib/landing_screen.dart
- lib/navigation/navigation_screen.dart
- lib/navigation/rerouting_handler.dart
- lib/positioning/positioning.dart
- lib/route_preferences/avoidance/country_avoidance_screen.dart
- lib/route_preferences/avoidance/road_features_avoidance_screen.dart
- lib/route_preferences/enum_string_helper.dart
- lib/route_preferences/pedestrian_options_screen.dart
- lib/route_preferences/route_text_options_widget.dart
- lib/route_preferences/scooter_options_screen.dart
- lib/route_preferences/truck_hazardous_materials_screen.dart
- lib/route_preferences/truck_options_screen.dart
- lib/route_preferences/truck_specifications_screen.dart
- lib/routing/route_details_screen.dart
- lib/routing/route_info_widget.dart
- lib/routing/route_poi_handler.dart
- lib/routing/route_waypoints_widget.dart
- lib/routing/routing_screen.dart
- lib/search/place_details_popup.dart
- lib/search/search_popup.dart
- lib/search/search_results_screen.dart
> Fixed deprecation warnings

- README.md
> README: Flutter 2.10.5 is required now

- lib/search/place_details_popup.dart
> Fix for opening urls

- android/app/src/main/kotlin/com/example/RefApp/MainActivity.kt
- lib/download_maps/download_maps_screen.dart
- lib/download_maps/map_regions_list_screen.dart
- lib/landing_screen.dart
- lib/navigation/navigation_screen.dart
- lib/route_preferences/avoidance/country_avoidance_screen.dart
- lib/route_preferences/avoidance/road_features_avoidance_screen.dart
- lib/route_preferences/route_preferences_screen.dart
- lib/route_preferences/truck_hazardous_materials_screen.dart
- lib/route_preferences/truck_specifications_screen.dart
- lib/routing/route_details_screen.dart
- lib/routing/routing_screen.dart
- lib/search/search_results_screen.dart
Keyboard no longer makes resize of layout and app will no longer draw
its content behind bottom system navigation bar.
> Fix for logo watermark

- lib/common/draggable_popup_here_logo_helper.dart
- lib/common/marquee_widget.dart
- lib/common/util.dart
- lib/download_maps/download_maps_screen.dart
- lib/l10n/app_en.arb
- lib/navigation/maneuver_action_text_helper.dart
- lib/navigation/navigation_screen.dart
- lib/route_preferences/dropdown_widget.dart
- lib/route_preferences/enum_string_helper.dart
- lib/routing/routing_screen.dart
- pubspec.lock
- pubspec.yaml
Removed deprecations for HERE SDK 4.12.10, deprecated MapUpdater
functions are still used (checkMapUpdate and performMapUpdate).
> Integrated HERE SDK 4.12.10 and Flutter 3.3.2

- ios/Flutter/AppFrameworkInfo.plist
- ios/Podfile.lock
- lib/common/place_actions_popup.dart
- lib/download_maps/map_regions_list_screen.dart
- lib/navigation/navigation_screen.dart
- lib/route_preferences/avoidance/country_avoidance_screen.dart
- lib/route_preferences/avoidance/road_features_avoidance_screen.dart
- lib/route_preferences/pedestrian_options_screen.dart
- lib/route_preferences/route_preferences_model.dart
- lib/route_preferences/route_text_options_widget.dart
- lib/route_preferences/scooter_options_screen.dart
- lib/route_preferences/truck_hazardous_materials_screen.dart
- lib/route_preferences/truck_options_screen.dart
- lib/route_preferences/truck_specifications_screen.dart
- lib/routing/route_poi_handler.dart
- lib/search/search_popup.dart
- pubspec.lock
- pubspec.yaml
Flutter 3.3.10 is now required.
Updated external dependencies to latest compatible versions.
> Integrated HERE SDK 4.13.0.

- README.md
> Updated required SDK and Flutter version numbers in README

- lib/landing_screen.dart
Cause:
- UI is not getting updated after user accepting the consent.
Fix:
- Wait for the user consent and then update UI.
Signed-off-by: manthri <119850631+mohan-manthri@users.noreply.github.com>
> Consent status not gets updated on acceptance just after fresh install

- l10n.yaml
- lib/common/marquee_widget.dart
- lib/common/reset_location_button.dart
- lib/common/ui_style.dart
- lib/download_maps/download_maps_screen.dart
- lib/l10n/app_en.arb
- lib/landing_screen.dart
- pubspec.lock
- pubspec.yaml
Upgrade Flutter version and resolve warnings and hints
- Updated Flutter to the most recent version.
- Addressed and resolved warnings and hints within the codebase.
- Fixed l10n arb file issues due to the Flutter 3.7.x
> Upgrade Flutter version and resolve warnings and hints

- README.md
- lib/common/draggable_popup_here_logo_helper.dart
- lib/download_maps/download_maps_screen.dart
- lib/download_maps/map_catalog_update_handler.dart
- lib/download_maps/map_loader_controller.dart
- lib/landing_screen.dart
- lib/navigation/maneuver_action_text_helper.dart
- lib/navigation/navigation_dialogs.dart
- lib/navigation/navigation_screen.dart
- lib/positioning/no_location_warning_widget.dart
- lib/route_preferences/transport_modes_widget.dart
- lib/routing/route_details_screen.dart
- lib/routing/route_waypoints_widget.dart
- lib/routing/routing_screen.dart
- lib/search/place_details_popup.dart
- lib/search/search_popup.dart
- lib/search/search_results_screen.dart
- pubspec.lock
- Upgraded HERE SDK to 4.14.0.0
- Updated watermark handling
- Updated handled flutter-svg color property
- Replaced deprecated mapUpdater APIs checkMapUpdate and performMapUpdate with the APIs retrieveCatalogsUpdateInfo and updateCatalog respectively.
> TICKET-T-17355:RefApp - Integrated latest HERE SDK

- ios/Podfile.lock
- lib/landing_screen.dart
- lib/positioning/positioning.dart
- Added engineStopped status check before showing positioning warning message
- Fixed locationEngine not restarted properly after relaunch.
> Fix positioning failed warn message when app terminated by back button

- lib/l10n/app_en.arb
- lib/main.dart
- lib/search/search_popup.dart
- lib/search/search_results_screen.dart
- Changed from **'Recent searches'** to **'Recent Search Results'**
- Removed the distance information when selecting from **'Recent Search Results'**
> TICKET-T-15806:RefApp - Fixed incorrect Route distance from recent searches

- lib/common/extensions/geo_box_extensions.dart
- lib/common/util.dart
- lib/routing/route_details_screen.dart
- Rewrote the route_details_screen with improved code logic.
- Enhanced handling of the bottom sheet to eliminate map blinking.
> Fixed map blinking when swiping the bottom sheet

- lib/download_maps/download_maps_screen.dart
- Since the API used to retrieve the list of downloadable regions operates async and may take some time to provide a response, this may appear to be the app not responding so
we have implemented a loading animation.
- We have implemented a check to determine whether the 'MapUpdate' option should be displayed, ensuring that it is only visible if it has not been initiated previously.
> TICKET-B-17757:RefApp-Fixed App freezing on 'Download Maps' button pressed

- android/app/src/main/kotlin/com/example/RefApp/MainActivity.kt
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info-Debug.plist
- ios/Runner/Info-Release.plist
- lib/common/battery_saver_utils.dart
- lib/common/device_info.dart
- lib/l10n/app_en.arb
- lib/landing_screen.dart
- lib/navigation/navigation_screen.dart
- lib/positioning/no_location_warning_widget.dart
- lib/positioning/positioning_engine.dart
- pubspec.lock
- pubspec.yaml
- Added always allow location permission to handle background navigation.
- Added battery saver warning dialog for real time navigation.
- Improved positioning engine code.
- Added support to navigate with screen lock.
- Landing screen will now show valid warning messages.
> TICKET-T-16950: RefApp - Support Navigation with screen lock 

- lib/positioning/positioning_engine.dart
- LocationPermission will be requested only once per app launch if not granted already.
- Code improvements.
> TICKET-T-16950-2: Fix Location permission issue

- README.md
- pubspec.lock
- pubspec.yaml
> Updated Flutter version

- lib/common/error_toast.dart
- lib/common/extensions/error_handling/map_loader_error_extension.dart
- lib/common/extensions/error_handling/routing_error_extension.dart
- lib/common/extensions/error_handling/search_error_extension.dart
- lib/common/ui_style.dart
- lib/download_maps/download_maps_screen.dart
- lib/l10n/app_en.arb
- lib/routing/routing_screen.dart
- lib/search/search_popup.dart
- Added extensions for RoutingError, SearchError and MapLoaderError to handle custom messages for Routing, Search and MapLoader.
- Added 'error_toast.dart' to display the error message.
> TICKET-T-17844:RefApp-Added custom messages for errors generated by HERE SDK

- ios/Runner/Base.lproj/LaunchScreen.storyboard
- lib/common/util.dart
- pubspec.yaml
- Updated RefApp version to 1.7.0
> TICKET-T-18614 : Updated version number

- ios/Podfile.lock
- pubspec.lock
- pubspec.yaml
- Updated external dependencies
> TICKET-T-18613: Update external dependencies

- lib/common/extensions/error_handling/search_error_extension.dart
- lib/search/search_popup.dart
> TICKET-T-17844: Ignoring toast for cancelled tasks

- lib/common/extensions/truck_specification_extensions.dart
- lib/l10n/app_en.arb
- lib/route_preferences/truck_options_screen.dart
- lib/route_preferences/truck_specifications_screen.dart
- Integrated weight per axle group.
- Arranged keys in arb file alphabetically.
> TICKET-T-19020: Integrated weight per axle group.

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- ios/Podfile.lock
- lib/download_maps/storage_space_widget.dart
- pubspec.lock
- pubspec.yaml
> TICKET-T-19083: Gradle version updated

- lib/navigation/navigation_screen.dart
- Enabled VisualNavigator route progress colors.
- Removed the route polyline added for the route progress view on the map.
> TICKET-T-17750:RefApp-Added support to show route progress colors.

- lib/search/search_results_screen.dart
- Removed distance information from search results list representation.
> TICKET-B-14123: Remove distance information

- lib/common/extensions/region_extensions.dart
- lib/download_maps/map_loader_controller.dart
- lib/download_maps/map_loader_dialogs.dart
- lib/download_maps/map_region_tile_widget.dart
- lib/download_maps/map_regions_list_screen.dart
- Cancelling parent region download now cancels, child region downloads.
> TICKET-B-17755: Fix Map downloader sub region installation issue

- lib/main.dart
- Moved the runApp to SDK initialisation success.
> Fix for grey screen on release mode

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- lib/common/ui_style.dart
- lib/navigation/navigation_screen.dart
- lib/route_preferences/route_preferences_screen.dart
- lib/routing/route_details_screen.dart
- lib/search/search_popup.dart
- lib/search/search_results_screen.dart
- pubspec.lock
- pubspec.yaml
- Upgraded to Flutter version 3.16.0
- Removed deprecated api WillPopScope to use PopScope
- Set the useMaterial3 to false to resolve the UI issue.
> Upgraded to the latest Flutter SDK version 3.16.0

- ios/Podfile.lock
- pubspec.lock
- pubspec.yaml
Updated external dependencies:
permission_handler: ^10.2.0 -> ^11.0.1
flutter_local_notifications: ^15.1.0+1 -> ^16.1.0
> TICKET-T-19788: Updated external dependencies

- ios/Runner/Base.lproj/LaunchScreen.storyboard
- lib/common/util.dart
- pubspec.yaml
Updated app version number to 1.8.0
> TICKET-T-19789: Updated app version number

- lib/navigation/navigation_screen.dart
Removed usage of uninitialised variable _mapRoute.
> TICKET-B-20663: Fix for rerouting after route deviation

- lib/download_maps/download_maps_screen.dart
- lib/download_maps/map_loader_controller.dart
- lib/download_maps/map_regions_list_screen.dart
- lib/landing_screen.dart
- Added error handling and displayed a toast message to the user.
- Ignoring the 'operationCancelled' error when displaying it to the user, but logging it to the console.
> TICKET-T-14032:Ref App Improved error handling for the 'download_maps_screen'

- lib/routing/routing_screen.dart
> TICKET-T-17742: Added maneuvers support in offline mode

- lib/download_maps/download_maps_screen.dart
- Fixed issue where sub region download is not cancelled when parent is cancelled.
> TICKET-B-17755: Fix cancel download issue.

- lib/download_maps/download_maps_screen.dart
- lib/routing/routing_screen.dart
- Including error codes in a toast for improved error notifications.
- Fixed dart analysis warning.
> TICKET-T-14032:RefApp Improved user notifications with error codes in toast msg

- ios/Podfile.lock
- lib/navigation/navigation_screen.dart
- pubspec.yaml
- Upgraded external dependencies to their latest resolvable versions.
- Migrated wakelock to wakelock plus package.
> TICKET-T-21504: Upgrade external dependencies

- ios/Podfile.lock
- ios/Runner/Base.lproj/LaunchScreen.storyboard
- lib/common/util.dart
- lib/landing_screen.dart
- pubspec.lock
- pubspec.yaml
- Upgraded version number from 1.8.0 to 1.9.0
- Extracting the app version dynamically from the build seems to be a good approach. Therefore, including code for the same.
> TICKET-T-21505:RefApp Upgraded version number to 1.9.0

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/example/RefApp/FlutterForegroundService.kt
- android/app/src/main/res/values/strings.xml
- Adapted new changes as required for Android 14.
- Added try-catch to platform code.
> TICKET-T-23365: Fix Realtime navigation crash on Android 14

- android/app/src/main/AndroidManifest.xml
- lib/common/local_notifications_helper.dart
- lib/navigation/navigation_screen.dart
- Requests permission for notification in Android 13 or later.
- [IOS] Last shown maneuver notification in navigation will get dismissed when app is resumed.
> TICKET-T-23723: Fix Android 14 notification permission

- README.md
- ios/Podfile.lock
- lib/common/extensions/error_handling/search_error_extension.dart
- lib/navigation/navigation_screen.dart
- lib/routing/route_poi_handler.dart
- pubspec.lock
> TICKET-T-24034: Integrate HERE SDK 4.18.0

- ios/Runner/Base.lproj/LaunchScreen.storyboard
- pubspec.yaml
> TICKET-T-24037: Version number update to 1.10.0

- android/app/build.gradle
- android/build.gradle
- android/settings.gradle
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/common/connection_state_monitor.dart
- pubspec.lock
- pubspec.yaml
- Updated external dependencies which are resolvable.
- Resolved gradle warnings in Android.
> TICKET-T-24036: Update external dependencies.

- lib/landing_screen.dart
Workaround to fix the issue of blank PlatformView on Android during app resume.
> TICKET-B-3150: Fix for blank screen on back button exit on Android

- README.md
- pubspec.lock
- pubspec.yaml
- Upgraded Flutter SDK version to '3.22.2'
- Updated Flutter version in README.md.
> TICKET-T-3541:RefApp Upgraded to the latest Flutter SDK version '3.22.2'

- pubspec.lock
- pubspec.yaml
Updated external dependencies which are resolvable.
> TICKET-T-3542: Updated external dependencies

- ios/Runner/Base.lproj/LaunchScreen.storyboard
- pubspec.yaml
Signed-off-by: Rahul Pant [14113872+mr-pant@users.noreply.github.com](mailto:14113872+mr-pant@users.noreply.github.com)
> TICKET-T-3543: Version number update to 1.11.0

- ios/Podfile.lock
- lib/routing/route_details_screen.dart
- lib/routing/routing_screen.dart
- lib/search/search_results_screen.dart
- pubspec.lock
- Integrated here_sdk version 4.19.0.
- Fixed deprecations related to the pick method by replacing the deprecated 'pickMapItems' with 'pick'.
> TICKET-T-3540: Integrated HERE SDK 4.19.0

- lib/landing_screen.dart
> Revert "TICKET-B-3150: Fix for blank screen on back button exit on Android (#153)"

- android/app/build.gradle
- android/build.gradle
- android/settings.gradle
- lib/common/battery_saver_utils.dart
- lib/common/error_toast.dart
- lib/common/notifications/android_notifications.dart
- lib/common/notifications/ios_notifications.dart
- lib/common/utils/navigation/location_providers/simulated_location_provider.dart
- lib/common/utils/navigation/location_utils.dart
- lib/download_maps/download_maps_screen.dart
- lib/download_maps/map_regions_list_screen.dart
- lib/landing_screen.dart
- lib/main.dart
- lib/navigation/navigation_screen.dart
- lib/positioning/positioning_engine.dart
- lib/route_preferences/truck_options_screen.dart
- lib/route_preferences/truck_specifications_screen.dart
- lib/routing/route_details_screen.dart
- lib/routing/route_waypoints_widget.dart
- lib/routing/routing_screen.dart
- lib/search/search_popup.dart
- pubspec.yaml
- Updated the 'name' field in 'pubspec.yaml' as per company policy and OSS guidelines.
- Updated files to accommodate the above changes as required.
- Added the HERE copyright header to files that were missing it
> TICKET-T-3233: Update package name in pubspec.yaml as per company policy

- lib/navigation/navigation_screen.dart
- Used FixedCameraBehavior when tapped on recenter
> TICKET-T-4091: Use FixedCameraBehavior

- ios/Podfile.lock
- pubspec.lock
- pubspec.yaml
Updated external dependencies which are resolvable.
> TICKET-T-4167: Updated external dependencies

- README.md
- ios/Podfile.lock
- lib/route_preferences/avoidance/country_avoidance_screen.dart
- lib/route_preferences/avoidance/road_features_avoidance_screen.dart
- lib/search/search_engine_proxy.dart
- pubspec.lock
- Integrated HERE SDK version 4.20.0.0
- Handled deprecations related to the upgrade.
- Updated the HERE SDK version in README.md to '4.20.0'.
> TICKET-T-4170: Integrated HERE SDK 4.20.0

- README.md
- android/app/build.gradle
- android/app/proguard-rules.pro
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- ios/Runner/Info-Debug.plist
- ios/Runner/Info-Release.plist
- lib/navigation/maneuver_action_text_helper.dart
- lib/route_preferences/enum_string_helper.dart
- pubspec.lock
- pubspec.yaml
- Upgraded the Flutter version of the HERE SDK Reference application from 3.24.3 to 3.27.2 and the Dart version from 3.5.3 to 3.6.1.
- Resolved deprecations.
- Updated Flutter version in README.md.
> TICKET-T-5456: Upgraded to the latest Flutter SDK version '3.27.2'

- lib/common/util.dart
Added a padding factor to the route's bounding box to ensure it fits properly on the screen and avoids overlapping with other views.
> TICKET-T-4945: Improved route visibility on the Route Overview screen

- README.md
- ios/Podfile.lock
- lib/main.dart
- pubspec.lock
- Integrated HERE SDK version 4.21.0.0
- Handled deprecations related to the upgrade.
- Updated the HERE SDK version in README.md to '4.21.0'.
> TICKET-T-5458: Integrated HERE SDK 4.21.0
